plugins {
    id 'java'
    id 'net.minecraftforge.gradle' version '[7.0.3,8)'
}

group = 'com.example.starforge'
version = '1.0.0'
base.archivesName = 'starforge'
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

minecraft {
    mappings channel: 'official', version: '1.21.1'
    runs {
        configureEach { workingDir = layout.projectDirectory.dir('run') }
        register('client')
    }
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
}

dependencies {
    implementation minecraft.dependency('net.minecraftforge:forge:1.21.1-52.1.16')
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
